### ISSUE TITLE
Data error during training in m-decoster-ChaLearn model

### ISSUE THREAD

**Issue by JoeNatan30** [gissemari/PeruvianSignLanguaje#2]
I followed this steps and got an error:

1. I preprocessed AEC data using shfiles (for AEC)
2. run sh files of chalearn classification model in order (1, 2, 3)
3. got this error during 3-runModel  and also during 4-runPrediction

```
Traceback (most recent call last):
  File "/home/cc/projects/joe/PeruvianSignLanguage/3.Classification/ChaLearn-2021-LAP/predict.py", line 68, in <module>
    for i, batch in enumerate(dataloader):
  File "/home/cc/miniconda3/envs/chalearn/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/cc/miniconda3/envs/chalearn/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/cc/miniconda3/envs/chalearn/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/cc/miniconda3/envs/chalearn/lib/python3.9/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cc/miniconda3/envs/chalearn/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cc/miniconda3/envs/chalearn/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/cc/miniconda3/envs/chalearn/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/cc/miniconda3/envs/chalearn/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/cc/miniconda3/envs/chalearn/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/cc/miniconda3/envs/chalearn/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/cc/miniconda3/envs/chalearn/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [15, 2, 3, 256, 256] at entry 0 and [6, 2, 3, 256, 256] at entry 2
```
I manually checked the video that generated the error and have different frames that it supposed to be

**Comment by JoeNatan30** [comment]
The problem was that there were some videos in Data/AEC/Videos/SEGMENTED_SIGN/ that had been created before.

When obtain_videos.py runs, it finds the video in both folders and takes the last one that finds.

I solved it after erase the videos I had been created some days before using
`find /path ! -newermt "YYYY-MM-DD HH:MM:SS" | xargs rm -rf`
 in each folder
